#!/usr/bin/osascript
# get current song

tell application "System Events"
  set myList to (name of every process)
end tell
if myList contains "Music" then
  tell application "Music"
    if player state is stopped then
      set output to "Stopped"
    else
      set trackname to name of current track
      set artistname to artist of current track
      set albumname to album of current track

      if player state is playing then
        set output to artistname & " - " & trackname
      else if player state is paused then
        set output to "⏸ " & artistname & " - " & trackname
      end if
    end if
  end tell
else
  set output to "Music not running"
end if
