#!/bin/sh

name=$1
if [ "$name" == "" ]; then
	read -p "Script name: " name
fi

path="/Users/koon/dev/scripts/$name"

if [ -f $path ]; then
	echo "$name already exists"
	exit 1
fi

echo "#!/bin/sh\n\n$2\n" > $path
chmod +x $path

if [ "$2" != "" ]; then
	exit 0
fi

nvim $path

